// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAPI1.Models;

namespace TestAPI1.Migrations
{
    [DbContext(typeof(LexiconContext))]
    partial class LexiconContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestAPI1.Models.Lexicon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Adjective");

                    b.Property<string>("Definition");

                    b.Property<string>("Name");

                    b.Property<string>("See1");

                    b.Property<string>("See2");

                    b.Property<string>("See3");

                    b.HasKey("Id");

                    b.ToTable("Lexicons");
                });
#pragma warning restore 612, 618
        }
    }
}
